-- 1. Create Companies Table
CREATE TABLE IF NOT EXISTS public.companies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Case-insensitive uniqueness index for company name
CREATE UNIQUE INDEX IF NOT EXISTS companies_name_lower_idx ON public.companies (LOWER(name));

-- 2. Alter Employees Table to Add Tenant Columns and Status
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS manager_id uuid;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'denied'));

-- 3. Alter other tables to support company_id scoping
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id) ON DELETE SET NULL;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id) ON DELETE SET NULL;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id) ON DELETE SET NULL;

-- 4. Create Role Permissions Table
CREATE TABLE IF NOT EXISTS public.role_permissions (
  company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('manager', 'employee')),
  module text NOT NULL,
  access_level text NOT NULL CHECK (access_level IN ('on', 'off')),
  PRIMARY KEY (company_id, role, module)
);

-- 5. Trigger Function to Populate Defaults for New Company
CREATE OR REPLACE FUNCTION public.handle_new_company_permissions()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.role_permissions (company_id, role, module, access_level) VALUES
    (NEW.id, 'manager', 'Employees', 'on'),
    (NEW.id, 'manager', 'Attendance', 'on'),
    (NEW.id, 'manager', 'Leave Management', 'on'),
    (NEW.id, 'manager', 'Performance', 'on'),
    (NEW.id, 'manager', 'Payroll', 'off'),
    (NEW.id, 'manager', 'Recruitment', 'off'),
    (NEW.id, 'manager', 'Attrition Analytics', 'off'),
    (NEW.id, 'manager', 'Employee Lifecycle', 'off'),
    (NEW.id, 'manager', 'Reports', 'off'),
    (NEW.id, 'manager', 'AI Copilot', 'on'),
    (NEW.id, 'manager', 'Notifications', 'on')
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger definition
DROP TRIGGER IF EXISTS on_company_created ON public.companies;
CREATE TRIGGER on_company_created
  AFTER INSERT ON public.companies
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_company_permissions();
