-- 1. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id uuid, -- target user (optional, e.g. a specific manager or employee)
  role text CHECK (role IN ('hr', 'manager', 'employee')), -- target role group
  type text NOT NULL,
  text text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Allow system to insert notifications" ON public.notifications;

-- Create Policies
CREATE POLICY "Users can read own notifications" ON public.notifications
  FOR SELECT TO authenticated
  USING (
    company_id IN (SELECT company_id FROM public.employees WHERE user_id = auth.uid()) AND
    (user_id = auth.uid() OR role = (SELECT role FROM public.employees WHERE user_id = auth.uid()))
  );

CREATE POLICY "Users can update own notifications" ON public.notifications
  FOR UPDATE TO authenticated
  USING (
    company_id IN (SELECT company_id FROM public.employees WHERE user_id = auth.uid()) AND
    (user_id = auth.uid() OR role = (SELECT role FROM public.employees WHERE user_id = auth.uid()))
  )
  WITH CHECK (
    company_id IN (SELECT company_id FROM public.employees WHERE user_id = auth.uid()) AND
    (user_id = auth.uid() OR role = (SELECT role FROM public.employees WHERE user_id = auth.uid()))
  );

CREATE POLICY "Allow system to insert notifications" ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- 2. Enforce Leave Approval via Database Trigger
CREATE OR REPLACE FUNCTION check_leave_request_update()
RETURNS TRIGGER AS $$
BEGIN
  -- If status is being changed (e.g. to approved or rejected)
  IF OLD.status IS DISTINCT FROM NEW.status THEN
    -- Check if current authenticated user is the manager of the employee
    IF NOT EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = OLD.employee_id AND e.manager_id = auth.uid()
    ) THEN
      RAISE EXCEPTION 'Only the assigned manager can approve or reject this leave request';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger to public.leave_requests
DROP TRIGGER IF EXISTS enforce_leave_request_status_update ON public.leave_requests;
CREATE TRIGGER enforce_leave_request_status_update
  BEFORE UPDATE ON public.leave_requests
  FOR EACH ROW
  EXECUTE FUNCTION check_leave_request_update();

-- 3. Automatic Notification trigger on Registration Pending
CREATE OR REPLACE FUNCTION public.handle_registration_notification()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'pending' THEN
    INSERT INTO public.notifications (company_id, role, type, text)
    VALUES (
      NEW.company_id,
      'hr',
      'registration_pending',
      CONCAT('New workspace registration request from ', NEW.full_name, ' (', NEW.role, ')')
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_registration_pending ON public.employees;
CREATE TRIGGER on_registration_pending
  AFTER INSERT OR UPDATE OF status ON public.employees
  FOR EACH ROW
  WHEN (NEW.status = 'pending')
  EXECUTE FUNCTION public.handle_registration_notification();
