-- 1. Create Candidates Table
CREATE TABLE IF NOT EXISTS public.candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_title text NOT NULL,
  resume_url text NOT NULL,
  candidate_name text,
  candidate_email text,
  ai_score integer,
  ai_summary text,
  matched_skills text[],
  missing_skills text[],
  stage text NOT NULL DEFAULT 'screening' CHECK (stage IN ('screening', 'interview', 'offer', 'rejected')),
  created_at timestamptz DEFAULT now()
);

-- 2. Enable RLS on Candidates Table
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing candidates policies if any
DROP POLICY IF EXISTS "HR can manage all candidates" ON public.candidates;
DROP POLICY IF EXISTS "Authenticated users can view candidates" ON public.candidates;

-- 4. Create Policies on Candidates Table
CREATE POLICY "HR can manage all candidates" ON public.candidates
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees 
      WHERE user_id = auth.uid() AND role = 'hr'
    )
  );

-- 5. Enable Storage RLS Policies for "resumes" bucket
-- Drop existing storage policies for resumes bucket to avoid conflicts
DROP POLICY IF EXISTS "Only HR can read resumes" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload resumes" ON storage.objects;
DROP POLICY IF EXISTS "HR can delete resumes" ON storage.objects;

-- 6. Create SELECT policy (Only HR can read/list files in resumes bucket)
CREATE POLICY "Only HR can read resumes" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'resumes' AND 
    EXISTS (
      SELECT 1 FROM public.employees 
      WHERE user_id = auth.uid() AND role = 'hr'
    )
  );

-- 7. Create INSERT policy (Authenticated users can upload files to resumes bucket)
CREATE POLICY "Authenticated users can upload resumes" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'resumes'
  );

-- 8. Create DELETE/UPDATE policy (HR can modify/delete files in resumes bucket)
CREATE POLICY "HR can delete resumes" ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'resumes' AND 
    EXISTS (
      SELECT 1 FROM public.employees 
      WHERE user_id = auth.uid() AND role = 'hr'
    )
  );
